org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dhttps.protocols=TLSv1.2,TLSv1.3
android.useAndroidX=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
kotlin.daemon.jvmargs=-Xmx2G
android.nativeBuildOutput=verbose
android.newDsl=false
kotlin.languageVersion=2.0
kotlin.apiVersion=2.0
org.gradle.project.android.nativeBuildOutput=verbose
systemProp.http.connectionTimeout=120000
systemProp.http.socketTimeout=120000
