include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    avoid_dynamic_calls: error
    strict_raw_types: error
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_dynamic_calls: true
    strict_raw_types: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    use_key_in_widget_constructors: true
    avoid_print: true
    avoid_empty_else: true
    empty_catches: true
    unnecessary_import: true
    unused_import: true
    unused_local_variable: true
    unused_field: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_relative_lib_imports: true
