// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<SandboxResult> sandboxExecute({
  required List<int> wasmBytes,
  required String functionName,
  required List<SandboxParam> params,
  SandboxConfig? config,
}) => RustLib.instance.api.crateApiSandboxExecute(
  wasmBytes: wasmBytes,
  functionName: functionName,
  params: params,
  config: config,
);

Future<bool> sandboxValidate({required List<int> wasmBytes}) =>
    RustLib.instance.api.crateApiSandboxValidate(wasmBytes: wasmBytes);

Future<List<SandboxExport>> sandboxListExports({
  required List<int> wasmBytes,
}) => RustLib.instance.api.crateApiSandboxListExports(wasmBytes: wasmBytes);
