// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SandboxConfig dco_decode_box_autoadd_sandbox_config(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SandboxExport> dco_decode_list_sandbox_export(dynamic raw);

  @protected
  List<SandboxParam> dco_decode_list_sandbox_param(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SandboxConfig? dco_decode_opt_box_autoadd_sandbox_config(dynamic raw);

  @protected
  SandboxConfig dco_decode_sandbox_config(dynamic raw);

  @protected
  SandboxExport dco_decode_sandbox_export(dynamic raw);

  @protected
  SandboxParam dco_decode_sandbox_param(dynamic raw);

  @protected
  SandboxResult dco_decode_sandbox_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SandboxConfig sse_decode_box_autoadd_sandbox_config(
    SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SandboxExport> sse_decode_list_sandbox_export(
    SseDeserializer deserializer);

  @protected
  List<SandboxParam> sse_decode_list_sandbox_param(
    SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SandboxConfig? sse_decode_opt_box_autoadd_sandbox_config(
    SseDeserializer deserializer);

  @protected
  SandboxConfig sse_decode_sandbox_config(SseDeserializer deserializer);

  @protected
  SandboxExport sse_decode_sandbox_export(SseDeserializer deserializer);

  @protected
  SandboxParam sse_decode_sandbox_param(SseDeserializer deserializer);

  @protected
  SandboxResult sse_decode_sandbox_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sandbox_config(
    SandboxConfig self,
    SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer);

  @protected
  void sse_encode_list_sandbox_export(
    List<SandboxExport> self,
    SseSerializer serializer);

  @protected
  void sse_encode_list_sandbox_param(
    List<SandboxParam> self,
    SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_sandbox_config(
    SandboxConfig? self,
    SseSerializer serializer);

  @protected
  void sse_encode_sandbox_config(SandboxConfig self, SseSerializer serializer);

  @protected
  void sse_encode_sandbox_export(SandboxExport self, SseSerializer serializer);

  @protected
  void sse_encode_sandbox_param(SandboxParam self, SseSerializer serializer);

  @protected
  void sse_encode_sandbox_result(SandboxResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
