// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SandboxConfig {
  final int maxMemoryMb;
  final BigInt maxExecutionTimeMs;
  final int maxStackDepth;
  final List<String> allowedCapabilities;

  const SandboxConfig({
    required this.maxMemoryMb,
    required this.maxExecutionTimeMs,
    required this.maxStackDepth,
    required this.allowedCapabilities,
  });

  @override
  int get hashCode =>
      maxMemoryMb.hashCode ^
      maxExecutionTimeMs.hashCode ^
      maxStackDepth.hashCode ^
      allowedCapabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandboxConfig &&
          runtimeType == other.runtimeType &&
          maxMemoryMb == other.maxMemoryMb &&
          maxExecutionTimeMs == other.maxExecutionTimeMs &&
          maxStackDepth == other.maxStackDepth &&
          allowedCapabilities == other.allowedCapabilities;
}

class SandboxExport {
  final String name;
  final String kind;

  const SandboxExport({required this.name, required this.kind});

  @override
  int get hashCode => name.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandboxExport &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind;
}

class SandboxParam {
  final String kind;
  final String value;

  const SandboxParam({required this.kind, required this.value});

  @override
  int get hashCode => kind.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandboxParam &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value;
}

class SandboxResult {
  final bool success;
  final String output;
  final BigInt executionTimeMs;
  final BigInt memoryUsedBytes;
  final String? error;

  const SandboxResult({
    required this.success,
    required this.output,
    required this.executionTimeMs,
    required this.memoryUsedBytes,
    this.error,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      output.hashCode ^
      executionTimeMs.hashCode ^
      memoryUsedBytes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandboxResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          output == other.output &&
          executionTimeMs == other.executionTimeMs &&
          memoryUsedBytes == other.memoryUsedBytes &&
          error == other.error;
}
